version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.1.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.19.0
    steps:
      - checkout
      - run: npm install --legacy-peer-deps
      - run: npm test
  push_to_registry:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - aws-ecr/build_and_push_image:
          dockerfile: Dockerfile
          auth:
            - aws-cli/setup
          repo: clmsg-backend
          tag: "0.1"

workflows:
  build_test_deploy:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: /^main/
      - push_to_registry:
          filters:
            branches:
              only: /^main/
