version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.19.0
    steps:
      - checkout
      - run: npm install --legacy-peer-deps

workflows:
  build_test_deploy:
    jobs:
      - build
